baseURL: https://yuanfan.xyz
languageCode: en-us
title: 阿木狗主
theme: "hugo-theme-mini"
paginate: 9

# for exampleSite only, you may need to delete the line: `themesDir: ../../` 

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/
  R-ME: /R-ME/:title/

googleAnalytics: your-google-analytics-id
disqusShortname: your-disqus-shortname

# Hugo Configure Markup
# see: https://gohugo.io/getting-started/configuration-markup#highlight
markup:
  highlight:
    guessSyntax: true
    style: emacs


# Social links in footer, support github,twitter,stackoverflow,facebook
social:
  # e.g.
  github: your-github-link
  twitter: your-github-link
  stackoverflow: your-github-link
  # facebook: your-facebook-link


# Site parameters
params:
  # Site Author
  author: 阿木狗主
  # Author biography
  bio: 这是yuanfan.vercel.app的备用域名，暂不启用，用来折(瞎)腾(碰)学(乱)习(试)
  # Site Description, used in HTML meat
  description: My Blog
  enableRSS: true
  # To enable comments, you may need to set `disqusShortname`
  enableComments: true
  # To enable comments, you may need to set `googleAnalytics`
  enableGoogleAnalytics: true

  # Optional
  home: '主页' # Default: Home
  about: '关于' # Default: About
  archive: '博客' # Default: Archive
  R-ME: 'R-ME'
  tags: '标签' # Default: Tags
  subscribe: '订阅' # Default: Subscribe
  olderPosts: '后面的猫' # Default: Older Posts
  newerPosts: '前面的狗' # Default: Newer Posts
  copyright: '© Copyright 2021 ❤️ 阿木狗主' # Default: © Copyright 2021 ❤️ author
  title404: '阿木狗主云游天外了' # Default: 404 - Page Not Found
  subtitle404: '' # Default: The content you're looking for doesn't seem to exist.
  readMore: '' # Default: Read More

  # Extra links in navigation
  links:
    # e.g.
    # - name: Project
    #   path: /project
